name: first

on: push

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v2
		- name: Step two
		  run: env | sort
	test:
		runs-on: windows-latest
		steps:
		- uses: actions/checkout@v2
		- name: Step two
		  run: "Get-ChildItem Env: | Sort-Object Name"

